In [ ]:
# ============================================
# TASK 2 - LOGISTICS DATA PREPROCESSING
# YuvaIntern Logistics Data Analyst Internship
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving olist_orders_dataset.csv to olist_orders_dataset.csv

In [ ]:
import os

print(os.listdir())

['.config', 'olist_orders_dataset.csv', 'sample_data']

In [ ]:
orders = pd.read_csv("olist_orders_dataset.csv")

print("Dataset loaded successfully!")
print("Number of rows:", orders.shape[0])
print("Number of columns:", orders.shape[1])

Dataset loaded successfully!
Number of rows: 99441
Number of columns: 8

In [ ]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
import pandas as pd
import numpy as np

orders = pd.read_csv("olist_orders_dataset.csv")

print("Shape:", orders.shape)
print("\nColumns:")
print(orders.columns.tolist())

Shape: (99441, 8)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [ ]:
print("Duplicate rows:", orders.duplicated().sum())
print("Duplicate order IDs:", orders["order_id"].duplicated().sum())

Duplicate rows: 0
Duplicate order IDs: 0

In [ ]:
print(orders["order_status"].value_counts())

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
missing = pd.DataFrame({
    "Missing Values": orders.isnull().sum(),
    "Missing %": (orders.isnull().sum() / len(orders) * 100).round(2)
})

missing

                               Missing Values  Missing %
order_id                                    0       0.00
customer_id                                 0       0.00
order_status                                0       0.00
order_purchase_timestamp                    0       0.00
order_approved_at                         160       0.16
order_delivered_carrier_date             1783       1.79
order_delivered_customer_date            2965       2.98
order_estimated_delivery_date               0       0.00

In [ ]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

print("Date conversion completed!")

Date conversion completed!

In [ ]:
orders[date_columns].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [ ]:
print(orders.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB
None

In [ ]:
delivered = orders[
    orders["order_status"] == "delivered"
].copy()

print("Total delivered orders:", len(delivered))
print(
    "Delivered orders with actual delivery date:",
    delivered["order_delivered_customer_date"].notna().sum()
)
print(
    "Delivered orders missing delivery date:",
    delivered["order_delivered_customer_date"].isna().sum()
)

Total delivered orders: 96478
Delivered orders with actual delivery date: 96470
Delivered orders missing delivery date: 8

In [ ]:
delivered[
    delivered["order_delivered_customer_date"].isna()
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [ ]:
delivered["delivery_time_days"] = (
    delivered["order_delivered_customer_date"]
    - delivered["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

In [ ]:
print(delivered["delivery_time_days"].describe())

count    96470.000000
mean        12.558217
std          9.546156
min          0.533414
25%          6.766204
50%         10.217477
75%         15.720182
max        209.628611
Name: delivery_time_days, dtype: float64

In [ ]:
delivered["delivery_delay_days"] = (
    delivered["order_delivered_customer_date"]
    - delivered["order_estimated_delivery_date"]
).dt.total_seconds() / (24 * 60 * 60)

In [ ]:
print(delivered["delivery_delay_days"].describe())

count    96470.000000
mean       -11.178126
std         10.184354
min       -146.016123
25%        -16.244065
50%        -11.948102
75%         -6.389815
max        188.975081
Name: delivery_delay_days, dtype: float64

In [ ]:
on_time = (
    delivered["delivery_delay_days"] <= 0
).sum()

late = (
    delivered["delivery_delay_days"] > 0
).sum()

total_with_delay = delivered["delivery_delay_days"].notna().sum()

on_time_rate = (on_time / total_with_delay) * 100
late_rate = (late / total_with_delay) * 100

print("Orders used for delay calculation:", total_with_delay)
print("On-Time/Early Orders:", on_time)
print("Late Orders:", late)
print(f"On-Time Delivery Rate: {on_time_rate:.2f}%")
print(f"Late Delivery Rate: {late_rate:.2f}%")

Orders used for delay calculation: 96470
On-Time/Early Orders: 88644
Late Orders: 7826
On-Time Delivery Rate: 91.89%
Late Delivery Rate: 8.11%

In [ ]:
missing_delivery = delivered[
    delivered["order_delivered_customer_date"].isna()
]

missing_delivery[
    [
        "order_id",
        "customer_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [ ]:
print(
    "Delivered orders missing customer delivery date:",
    len(missing_delivery)
)

Delivered orders missing customer delivery date: 8

In [ ]:
negative_delivery_time = delivered[
    delivered["delivery_time_days"] < 0
]

print(
    "Negative delivery-time records:",
    len(negative_delivery_time)
)

Negative delivery-time records: 0

In [ ]:
print(
    "Delivery time <= 1 day:",
    (delivered["delivery_time_days"] <= 1).sum()
)

Delivery time <= 1 day: 13

In [ ]:
Q1 = delivered["delivery_time_days"].quantile(0.25)
Q3 = delivered["delivery_time_days"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Q1: {Q1:.2f}")
print(f"Q3: {Q3:.2f}")
print(f"IQR: {IQR:.2f}")
print(f"Lower Bound: {lower_bound:.2f}")
print(f"Upper Bound: {upper_bound:.2f}")

Q1: 6.77
Q3: 15.72
IQR: 8.95
Lower Bound: -6.66
Upper Bound: 29.15

In [ ]:
outliers = delivered[
    (delivered["delivery_time_days"] < lower_bound) |
    (delivered["delivery_time_days"] > upper_bound)
]

print(
    "Potential delivery-time outliers:",
    len(outliers)
)

Potential delivery-time outliers: 4896

In [ ]:
# FAST TASK 2 PREPROCESSING

import pandas as pd
import numpy as np

# Work only with delivered orders having actual delivery dates
task2_data = orders[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_customer_date"].notna())
].copy()

# Delivery time
task2_data["delivery_time_days"] = (
    task2_data["order_delivered_customer_date"]
    - task2_data["order_purchase_timestamp"]
).dt.total_seconds() / 86400

# Delivery delay
task2_data["delivery_delay_days"] = (
    task2_data["order_delivered_customer_date"]
    - task2_data["order_estimated_delivery_date"]
).dt.total_seconds() / 86400

# Early / On-Time / Late classification
task2_data["delivery_performance"] = np.where(
    task2_data["delivery_delay_days"] < 0,
    "Early",
    np.where(
        task2_data["delivery_delay_days"] == 0,
        "On Time",
        "Late"
    )
)

# Late delivery flag
task2_data["late_delivery"] = np.where(
    task2_data["delivery_delay_days"] > 0,
    1,
    0
)

# IQR outlier flag
Q1 = task2_data["delivery_time_days"].quantile(0.25)
Q3 = task2_data["delivery_time_days"].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

task2_data["delivery_time_outlier"] = np.where(
    task2_data["delivery_time_days"] > upper_bound,
    1,
    0
)

# Save final dataset
task2_data.to_csv(
    "Olist_Task2_Preprocessed_Data.csv",
    index=False
)

# Final summary
print("===== TASK 2 COMPLETE =====")
print("Original records:", len(orders))
print("Final analysis records:", len(task2_data))
print("Average delivery time:",
      round(task2_data["delivery_time_days"].mean(), 2), "days")
print("Average delivery delay:",
      round(task2_data["delivery_delay_days"].mean(), 2), "days")
print("Late orders:",
      task2_data["late_delivery"].sum())
print("Potential outliers:",
      task2_data["delivery_time_outlier"].sum())
print("File saved: Olist_Task2_Preprocessed_Data.csv")

===== TASK 2 COMPLETE =====
Original records: 99441
Final analysis records: 96470
Average delivery time: 12.56 days
Average delivery delay: -11.18 days
Late orders: 7826
Potential outliers: 4896
File saved: Olist_Task2_Preprocessed_Data.csv

# New Section

In [ ]:
from google.colab import files
files.download("Olist_Task2_Preprocessed_Data.csv")

In [ ]:
task2_data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time_days,delivery_delay_days,delivery_performance,late_delivery,delivery_time_outlier
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.436574,-7.107488,Early,0,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.782037,-5.355729,Early,0,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.394213,-17.245498,Early,0,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.208750,-12.980069,Early,0,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.873877,-9.238171,Early,0,0

In [ ]:
task2_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96470 entries, 0 to 99440
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96470 non-null  object
 1   customer_id                    96470 non-null  object
 2   order_status                   96470 non-null  object
 3   order_purchase_timestamp       96470 non-null  datetime64[ns]
 4   order_approved_at              96456 non-null  datetime64[ns]
 5   order_delivered_carrier_date   96469 non-null  datetime64[ns]
 6   order_delivered_customer_date  96470 non-null  datetime64[ns]
 7   order_estimated_delivery_date  96470 non-null  datetime64[ns]
 8   delivery_time_days             96470 non-null  float64
 9   delivery_delay_days            96470 non-null  float64
 10  delivery_performance           96470 non-null  object
 11  late_delivery                  96470 non-null  int64
 12  delivery_time_outlier          96470 non-null  int64
dtypes: datetime64[ns](5), float64(2), int64(2), object(4)
memory usage: 10.3+ MB

In [ ]:
print("===== OUTLIER DETECTION =====")
print(f"Q1: {Q1:.2f} days")
print(f"Q3: {Q3:.2f} days")
print(f"IQR: {IQR:.2f} days")
print(f"Lower Bound: {lower_bound:.2f} days")
print(f"Upper Bound: {upper_bound:.2f} days")
print(f"Potential Outliers: {len(outliers)}")
print(
    "Negative Delivery-Time Records:",
    (task2_data["delivery_time_days"] < 0).sum()
)

===== OUTLIER DETECTION =====
Q1: 6.77 days
Q3: 15.72 days
IQR: 8.95 days
Lower Bound: -6.66 days
Upper Bound: 29.15 days
Potential Outliers: 4896
Negative Delivery-Time Records: 0